{
 "title": "LeakMonitor - Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "LastRun",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "leakmonitor_last_run_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SinceStart",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(time() - leakmonitor_last_run_timestamp) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalRuns",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "leakmonitor_runs_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NewLeaks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(leakmonitor_new_leaks_total[24h])\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(leakmonitor_new_leaks_total[24h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RowsFetched",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "increase(leakmonitor_rows_fetched_total[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(leakmonitor_query_duration_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RareLimit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(leakmonitor_rate_limited_total[1h])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}